CREATE TABLE IF NOT EXISTS `tb_user` (
    id LONG NOT NULL PRIMARY KEY,
    full_name VARCHAR(70) NOT NULL,
    email VARCHAR(70) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    cpf VARCHAR(11) NOT NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

);