CREATE TABLE IF NOT EXISTS `TB_PARKING_SPACE` (
    ID LONG NOT NULL PRIMARY KEY,
    CONDOMINIUM_BLOCK VARCHAR(40) NOT NULL,
    CONDOMINIUM_APARTMENT VARCHAR(40) NOT NULL,
    VEHICLE_BRAND VARCHAR(70) NOT NULL,
    VEHICLE_MODEL VARCHAR(70) NOT NULL,
    VEHICLE_COLOR VARCHAR(70) NOT NULL,
    RESPONSIBLE_VEHICLE_NAME VARCHAR(140) NOT NULL,
    VEHICLE_SPACE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    VEHICLE_LICENSE_PLATE_NUMBER VARCHAR(7) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    USER_ID LONG NOT NULL PRIMARY KEY,
    VEHICLE_ID LONG NOT NULL PRIMARY KEY

    CONSTRAINTS FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID)
    CONSTRAINTS FOREIGN KEY (VEHICLE_ID) REFERENCES TB_VEHICLE(ID)
);