CREATE TABLE IF NOT EXISTS `TB_VEHICLE` (
    id LONG NOT NULL PRIMARY KEY,
    brand VARCHAR(70) NOT NULL,
    model VARCHAR(70) NOT NULL,
    color VARCHAR(70) NOT NULL,
    space_number VARCHAR(10) NOT NULL UNIQUE,
    license_plate_number VARCHAR(7) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    user_id LONG NOT NULL UNIQUE

    CONSTRAINTS FOREIGN KEY (user_id) REFERENCES tb_user(id)

);