CREATE TABLE IF NOT EXISTS `TB_VEHICLE` (
    ID LONG NOT NULL PRIMARY KEY,
    BRAND VARCHAR(70) NOT NULL,
    MODEL VARCHAR(70) NOT NULL,
    COLOR VARCHAR(70) NOT NULL,
    SPACE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    LICENSE_PLATE_NUMBER VARCHAR(7) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    USER_ID LONG NOT NULL UNIQUE

    CONSTRAINTS FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID)

);